### ISSUE TITLE
allow more then 3 navlinks?

### ISSUE THREAD

**Issue by finki70** [shaansubbaiah/Portfolio#15] opened 2020-10-02 06:57 UTC
maybe, some users want more then 3 navlinks, I think that couls be a nice hacktoberfest issue :)

**Comment by shaansubbaiah** [comment] 2020-10-02 07:04
I honestly think most people will add other links in info-links (links under the profile image) rather than the nav-links (links on the top right, eg. for Resume). 
If you want to take it up, please feel free to :smile:

**Comment by shaansubbaiah** [comment] 2020-10-02 07:32
I think we can add more than 3 already, just by changing the limit in `build.js`. The issue is that it is visually unappealing.

**Comment by ankitaugale23** [comment] 2020-10-02 10:30
Can I work on this?

**Comment by shaansubbaiah** [comment] 2020-10-03 05:14
@ankitaugale23 thanks for your interest! You can contribute towards fixing the other issues.

I've decided to limit the navlinks to 3 and custom infolinks to 4. Closing this.

**Closed by shaansubbaiah** 2020-10-03 05:14 UTC
Labels: good first issue, hacktoberfest, hacktoberfest2020
